In [1]:
import numpy as np

## 1. NumPy DataTypes and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1, 2, 3.3], 
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [4]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

![](numpy-anatomy-of-a-numpy-array.png)

In [5]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [6]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [8]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating NumPy Arrays

In [11]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [12]:
sample_array.dtype

dtype('int64')

In [13]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
ones.dtype

dtype('float64')

In [15]:
type(ones)

numpy.ndarray

In [16]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 9, 8, 7, 6],
       [5, 4, 2, 5, 0],
       [8, 2, 6, 4, 4]])

In [19]:
random_array.size

15

In [20]:
random_array.shape

(3, 5)

In [21]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.20952227, 0.38699276, 0.22127612],
       [0.12875759, 0.30835055, 0.46916652],
       [0.88989141, 0.59940234, 0.04219446],
       [0.34731047, 0.6373707 , 0.40048682],
       [0.43836131, 0.8229596 , 0.68094643]])

In [22]:
random_array_2.shape

(5, 3)

In [23]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.68808675, 0.93447204, 0.60557061],
       [0.23368844, 0.51855657, 0.19568425],
       [0.08633163, 0.27671105, 0.24621643],
       [0.49340078, 0.55324617, 0.59631445],
       [0.75405224, 0.84375574, 0.41671995]])

In [24]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [25]:
random_array_4.shape

(5, 3)

In [26]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [27]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## 3. Viewing Arrays and Matrices

In [29]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a1

array([1, 2, 3])

In [31]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a1[0]

1

In [34]:
a2[0]

array([1. , 2. , 3.3])

In [35]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a2[1]

array([4. , 5. , 6.5])

In [37]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [40]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[1, 1, 5, 3, 2],
         [0, 4, 8, 7, 1],
         [4, 9, 3, 6, 7],
         [1, 0, 2, 7, 0]],

        [[0, 9, 8, 2, 0],
         [5, 5, 0, 9, 0],
         [8, 4, 5, 1, 4],
         [0, 7, 2, 0, 3]],

        [[9, 8, 3, 7, 1],
         [0, 1, 4, 6, 1],
         [0, 1, 0, 1, 8],
         [4, 1, 6, 8, 5]]],


       [[[2, 4, 7, 4, 1],
         [2, 8, 5, 2, 9],
         [6, 2, 5, 7, 7],
         [5, 5, 6, 0, 6]],

        [[4, 6, 2, 6, 8],
         [7, 0, 5, 8, 9],
         [7, 7, 6, 2, 5],
         [6, 1, 9, 3, 4]],

        [[0, 3, 5, 6, 4],
         [0, 4, 1, 5, 2],
         [4, 8, 7, 5, 7],
         [5, 3, 7, 6, 2]]]])

In [41]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [42]:
# Get the first 4 numbers of the inner most arrays


In [43]:
a4[:, :, :, :4]

array([[[[1, 1, 5, 3],
         [0, 4, 8, 7],
         [4, 9, 3, 6],
         [1, 0, 2, 7]],

        [[0, 9, 8, 2],
         [5, 5, 0, 9],
         [8, 4, 5, 1],
         [0, 7, 2, 0]],

        [[9, 8, 3, 7],
         [0, 1, 4, 6],
         [0, 1, 0, 1],
         [4, 1, 6, 8]]],


       [[[2, 4, 7, 4],
         [2, 8, 5, 2],
         [6, 2, 5, 7],
         [5, 5, 6, 0]],

        [[4, 6, 2, 6],
         [7, 0, 5, 8],
         [7, 7, 6, 2],
         [6, 1, 9, 3]],

        [[0, 3, 5, 6],
         [0, 4, 1, 5],
         [4, 8, 7, 5],
         [5, 3, 7, 6]]]])