In [1]:
import numpy as np

## 1. NumPy DataTypes and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1, 2, 3.3], 
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [4]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

![](numpy-anatomy-of-a-numpy-array.png)

In [5]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [6]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [8]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating NumPy Arrays

In [11]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [12]:
sample_array.dtype

dtype('int64')

In [13]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
ones.dtype

dtype('float64')

In [15]:
type(ones)

numpy.ndarray

In [16]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[0, 7, 4, 8, 6],
       [9, 8, 6, 5, 8],
       [2, 6, 3, 7, 3]])

In [19]:
random_array.size

15

In [20]:
random_array.shape

(3, 5)

In [21]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.71693   , 0.79637157, 0.62965754],
       [0.23821702, 0.34103869, 0.73194448],
       [0.54963488, 0.98659449, 0.13364323],
       [0.5250246 , 0.80779297, 0.33738729],
       [0.53416057, 0.07455377, 0.15530093]])

In [22]:
random_array_2.shape

(5, 3)

In [23]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.37942212, 0.52817575, 0.5280711 ],
       [0.57368081, 0.91663241, 0.08349159],
       [0.52490839, 0.52620588, 0.99908434],
       [0.91317691, 0.14755743, 0.1875607 ],
       [0.34699513, 0.93795543, 0.10660476]])

In [30]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [32]:
random_array_4.shape

(5, 3)

In [37]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [38]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])