In [1]:
import numpy as np

## 1. NumPy DataTypes and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1, 2, 3.3], 
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [4]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

![](numpy-anatomy-of-a-numpy-array.png)

In [5]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [6]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [8]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating NumPy Arrays

In [12]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [13]:
sample_array.dtype

dtype('int64')

In [14]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
ones.dtype

dtype('float64')

In [16]:
type(ones)

numpy.ndarray

In [17]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 2, 0, 4, 1],
       [3, 3, 1, 9, 6],
       [1, 5, 7, 2, 9]])

In [29]:
random_array.size

15

In [30]:
random_array.shape

(3, 5)

In [31]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.51706837, 0.29813294, 0.20169968],
       [0.19607236, 0.36366211, 0.94006616],
       [0.53178365, 0.10356617, 0.6031496 ],
       [0.78136125, 0.42501306, 0.02409916],
       [0.03870742, 0.49400229, 0.75299673]])

In [32]:
random_array_2.shape

(5, 3)

In [33]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.37091631, 0.02713706, 0.60779063],
       [0.52368212, 0.55908175, 0.38624762],
       [0.4647851 , 0.47336873, 0.15702721],
       [0.75915042, 0.27339064, 0.00649458],
       [0.70699521, 0.35879416, 0.4900741 ]])

In [34]:
# Pseudo-random numbers
np.random.seed()